package edu.cs3500.spreadsheets.provider.view;


import edu.cs3500.spreadsheets.provider.controller.SpreadsheetFeatures;
import edu.cs3500.spreadsheets.model.Coord;
import edu.cs3500.spreadsheets.provider.model.ReadOnlyWorksheetModel;

/**
 * Contains functionality to depict the data in the worksheet. Note: not all functionality may be
 * supported by all implementing classes.
 */
public interface WorksheetView {

  /**
   * Renders the current contents of the model in some way.
   */
  void refresh();

  /**
   * Adds the given SpreadsheetFeatures to the view such that the sf will respond to events that
   * were generated by the view.
   *
   * @param sf the SpreadsheetFeatures to add to the view
   */
  void addSpreadsheetFeatures(SpreadsheetFeatures sf);

  /**
   * Renders the cell at the given location as highlighted and indicates that it is selected.
   * Unhighlights the previous cell that was being highlighted.
   *
   * @param loc cell location to highlight at
   */
  void highlightAt(Coord loc);

  /**
   * Removes highlighting for the whole sheet; essentially displays the sheet as its default state.
   */
  void turnOffHighlight();

  /**
   * Displays the given message in some form to the user.
   *
   * @param message the message to display
   */
  void displayMsg(String message);

  /**
   * Changes the model for the view so that it displays the new one instead of the previous one.
   * @param model the new model that will be shown on the view
   */
  void changeModel(ReadOnlyWorksheetModel model);

}
