package edu.cs3500.spreadsheets.model;

import java.util.List;

/**
 * To represent a view only spreadsheet. Users that use this interface cannot
 * mutate the model, so it is used only so the view cannot mutate the model directly.
 */
public interface ISpreadsheetViewOnly {
  /**
   * Gets the formula used at a certain cell.
   *
   * @param coord coordinate of cell
   * @return formula that user inputted
   */
  Formula getFormulaAtCoord(Coord coord);

  /**
   * Evaluates the given cell and returns a value.
   *
   * @param coord coordinate of cell
   * @return A Value representation of cell input
   */
  Value evaluateCell(Coord coord);

  /**
   * Gets the list of error messages generated by this spreadsheet during creation of cells.
   *
   * @return list of error messages
   */
  List<String> errorMessages();

  /**
   * Gets the list of occupied Coords in this spreadsheet.
   *
   * @return list of Coord.
   */
  List<Coord> getOccupiedCoords();

  /**
   * Gets the number of columns displayed in the spreadsheet view.
   */
  int getCol();

  /**
   * Gets the number of rows displayed in the spreadsheet view.
   */
  int getRow();

}
